# Generated by Django 5.0.4 on 2024-05-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://res.cloudinary.com/dtajxn9oi/image/upload/v1712323984/Drf-api/default_profile_ubr0la.jpg', upload_to='images'),
        ),
    ]
