# Generated by Django 5.0.4 on 2024-05-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='Drf-api/default_profile_ubr0la', upload_to='images'),
        ),
    ]
