# Generated by Django 3.2.4 on 2024-07-07 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        ('like_review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likereview',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_likes', to='reviews.review'),
        ),
    ]
