# Generated by Django 5.0.4 on 2024-05-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='link',
            field=models.URLField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
