# Generated by Django 5.0.4 on 2024-05-07 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='../default_product_rgq6aq', upload_to='images/'),
        ),
    ]
